// Code generated by go generate; DO NOT EDIT.
package commands

import (
	"github.com/brandonc/advent2024/solutions/day01"
	"github.com/brandonc/advent2024/solutions/day02"
	"github.com/brandonc/advent2024/solutions/day03"
	"github.com/brandonc/advent2024/solutions/day04"
	"github.com/brandonc/advent2024/solutions/day05"
	"github.com/brandonc/advent2024/solutions/day06"
	"github.com/brandonc/advent2024/solutions/day07"
	"github.com/brandonc/advent2024/solutions/day08"
	"github.com/brandonc/advent2024/solutions/day09"
	"github.com/brandonc/advent2024/solutions/day10"
	"github.com/brandonc/advent2024/solutions/day11"
	"github.com/brandonc/advent2024/solutions/day12"
	"github.com/brandonc/advent2024/solutions/day13"
	"github.com/brandonc/advent2024/solutions/day14"
	"github.com/brandonc/advent2024/solutions/solution"
)

var SolutionCommands = map[string]solution.SolutionFactory{
	"1": day01.Factory,
	"2": day02.Factory,
	"3": day03.Factory,
	"4": day04.Factory,
	"5": day05.Factory,
	"6": day06.Factory,
	"7": day07.Factory,
	"8": day08.Factory,
	"9": day09.Factory,
	"10": day10.Factory,
	"11": day11.Factory,
	"12": day12.Factory,
	"13": day13.Factory,
	"14": day14.Factory,
}
